---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on node
    apt:
      name: apache2
      state: present
      when: ansible_os_family =="Debian"

  - name: i want to start web service on ansible node
    service:
      name: apache2
      state: started
      when: ansible_os_family =="Debian"
      
